name: 'Hetzner Cloud Doorkeeper'
description: 'Open and closes a specific IP/Port on a Hetzner Cloud firewall'
inputs:
  hcloud_token:
    description: 'Hetzner Cloud token to access the Firewall'
    required: true
  firewall_name:
    description: 'Name of firewall to configure'
    required: true
  ip:
    description: 'CIDR representation of IP range to allow access (Defaults to current runner IP)'
    required: false
  port:
    description: 'Port to open'
    required: false
    default: 22
  protocol:
    description: 'Protocol for the above port. Either `tcp` or `udp`'
    required: false
    default: 'tcp'
  autoclean:
    description: 'Automatically clean up the opened port after the workflow finishes'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  post-entrypoint: '/delete.sh'
  #post-if: ${{ inputs.autoclean == 'true' }}
  env:
    HCLOUD_TOKEN: ${{ inputs.hcloud_token }} 